apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-mlb-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-mlb-stats
  template:
    metadata:
      labels:
        app: discord-mlb-stats
    spec:
      containers:
        - name: discord-mlb-stats
          image: localhost:32000/discord-mlb-stats:latest
          env:
            - name: DISCORD_MLB_STATS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-mlb-stats-token
                  key: DISCORD_MLB_STATS_TOKEN
